[package]
name = "mb-engine"
version.workspace = true
edition.workspace = true
description = "Playback engine for masterblaster tracker"

[features]
default = ["std"]
std = ["mb-ir/std"]

[dependencies]
mb-ir = { workspace = true }
heapless = { workspace = true }
